"""Add spectral_templates

Revision ID: 2eb6e5e46115
Revises: 0006
Create Date: 2026-05-12 05:19:02.899445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eb6e5e46115'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spectral_templates',
    sa.Column('template_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('molecule', sa.Text(), nullable=False),
    sa.Column('temperature_k', sa.Float(), nullable=False),
    sa.Column('pressure_bar', sa.Float(), nullable=False),
    sa.Column('instrument_resolution', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index('ix_spectral_templates_lookup', 'spectral_templates', ['molecule', 'temperature_k'], unique=False)
    op.create_index(op.f('ix_spectral_templates_molecule'), 'spectral_templates', ['molecule'], unique=False)
    op.drop_index(op.f('idx_exomol_mol_wl'), table_name='exomol_lines_curated')
    op.drop_table('exomol_lines_curated')
    op.drop_index(op.f('ix_ppm_paper_id'), table_name='paper_planet_mentions')
    op.drop_index(op.f('ix_ppm_planet_id'), table_name='paper_planet_mentions')
    op.drop_index(op.f('ix_ppm_star_id'), table_name='paper_planet_mentions')
    op.drop_table('paper_planet_mentions')
    op.drop_index(op.f('ix_anomaly_planet_id'), table_name='anomaly_flags')
    op.drop_index(op.f('ix_anomaly_reviewed'), table_name='anomaly_flags')
    op.drop_index(op.f('ix_anomaly_sigma'), table_name='anomaly_flags')
    op.create_index(op.f('ix_anomaly_flags_deviation_sigma'), 'anomaly_flags', ['deviation_sigma'], unique=False)
    op.create_index(op.f('ix_anomaly_flags_planet_id'), 'anomaly_flags', ['planet_id'], unique=False)
    op.create_index(op.f('ix_anomaly_flags_reviewed'), 'anomaly_flags', ['reviewed'], unique=False)
    op.drop_index(op.f('ix_atm_spectra_facility'), table_name='atmospheric_spectra')
    op.drop_index(op.f('ix_atm_spectra_planet_id'), table_name='atmospheric_spectra')
    op.drop_index(op.f('ix_atm_spectra_planet_name'), table_name='atmospheric_spectra')
    op.drop_index(op.f('ix_atm_spectra_spec_id'), table_name='atmospheric_spectra')
    op.drop_index(op.f('ix_atm_spectra_wavelength'), table_name='atmospheric_spectra')
    op.create_index(op.f('ix_atmospheric_spectra_facility'), 'atmospheric_spectra', ['facility'], unique=False)
    op.create_index(op.f('ix_atmospheric_spectra_planet_id'), 'atmospheric_spectra', ['planet_id'], unique=False)
    op.create_index(op.f('ix_atmospheric_spectra_planet_name'), 'atmospheric_spectra', ['planet_name'], unique=False)
    op.create_index(op.f('ix_atmospheric_spectra_spec_id'), 'atmospheric_spectra', ['spec_id'], unique=False)
    op.create_index(op.f('ix_atmospheric_spectra_wavelength_um'), 'atmospheric_spectra', ['wavelength_um'], unique=False)
    op.drop_index(op.f('ix_biosig_confidence'), table_name='biosignature_detections')
    op.drop_index(op.f('ix_biosig_molecule'), table_name='biosignature_detections')
    op.drop_index(op.f('ix_biosig_planet_id'), table_name='biosignature_detections')
    op.create_index(op.f('ix_biosignature_detections_detection_confidence'), 'biosignature_detections', ['detection_confidence'], unique=False)
    op.create_index(op.f('ix_biosignature_detections_molecule'), 'biosignature_detections', ['molecule'], unique=False)
    op.create_index(op.f('ix_biosignature_detections_planet_id'), 'biosignature_detections', ['planet_id'], unique=False)
    op.drop_index(op.f('ix_habitability_composite'), table_name='habitability_scores', postgresql_where='(composite_score IS NOT NULL)')
    op.drop_index(op.f('ix_habitability_planet_id'), table_name='habitability_scores')
    op.create_index(op.f('ix_habitability_scores_planet_id'), 'habitability_scores', ['planet_id'], unique=False)
    op.drop_index(op.f('ix_hitran_molecule'), table_name='hitran_lines')
    op.drop_index(op.f('ix_hitran_wavelength'), table_name='hitran_lines')
    op.create_index(op.f('ix_hitran_lines_molecule'), 'hitran_lines', ['molecule'], unique=False)
    op.create_index(op.f('ix_hitran_lines_wavelength_um'), 'hitran_lines', ['wavelength_um'], unique=False)
    op.drop_index(op.f('ix_mol_det_molecule'), table_name='molecule_detections')
    op.drop_index(op.f('ix_mol_det_planet_id'), table_name='molecule_detections')
    op.drop_index(op.f('ix_mol_det_reviewed'), table_name='molecule_detections')
    op.drop_index(op.f('ix_mol_det_sigma'), table_name='molecule_detections')
    op.create_index(op.f('ix_molecule_detections_detection_sigma'), 'molecule_detections', ['detection_sigma'], unique=False)
    op.create_index(op.f('ix_molecule_detections_molecule'), 'molecule_detections', ['molecule'], unique=False)
    op.create_index(op.f('ix_molecule_detections_planet_id'), 'molecule_detections', ['planet_id'], unique=False)
    op.create_index(op.f('ix_molecule_detections_reviewed'), 'molecule_detections', ['reviewed'], unique=False)
    op.drop_index(op.f('ix_orbital_predictions_unconfirmed'), table_name='orbital_predictions', postgresql_where='(confirmed_by_planet_id IS NULL)')
    op.drop_constraint(op.f('papers_arxiv_id_key'), 'papers', type_='unique')
    op.drop_constraint(op.f('papers_doi_key'), 'papers', type_='unique')
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.drop_index(op.f('ix_planet_params_planet_id'), table_name='planet_parameters')
    op.create_index(op.f('ix_planet_parameters_planet_id'), 'planet_parameters', ['planet_id'], unique=False)
    op.drop_index(op.f('ix_planets_planet_name'), table_name='planets')
    op.create_unique_constraint(None, 'planets', ['planet_name'])
    op.drop_index(op.f('ix_star_params_star_id'), table_name='star_parameters')
    op.create_index(op.f('ix_star_parameters_star_id'), 'star_parameters', ['star_id'], unique=False)
    op.drop_index(op.f('ix_stars_hip_name'), table_name='stars')
    op.drop_index(op.f('ix_stars_ra_dec'), table_name='stars')
    op.drop_index(op.f('ix_stars_spectral_type'), table_name='stars')
    op.create_unique_constraint(None, 'stars', ['hip_name'])
    op.drop_index(op.f('ix_taxonomy_cluster_run_id'), table_name='taxonomy_clusters')
    op.drop_index(op.f('ix_taxonomy_planet_id'), table_name='taxonomy_clusters')
    op.create_index(op.f('ix_taxonomy_clusters_cluster_run_id'), 'taxonomy_clusters', ['cluster_run_id'], unique=False)
    op.create_index(op.f('ix_taxonomy_clusters_planet_id'), 'taxonomy_clusters', ['planet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxonomy_clusters_planet_id'), table_name='taxonomy_clusters')
    op.drop_index(op.f('ix_taxonomy_clusters_cluster_run_id'), table_name='taxonomy_clusters')
    op.create_index(op.f('ix_taxonomy_planet_id'), 'taxonomy_clusters', ['planet_id'], unique=False)
    op.create_index(op.f('ix_taxonomy_cluster_run_id'), 'taxonomy_clusters', ['cluster_run_id'], unique=False)
    op.drop_constraint(None, 'stars', type_='unique')
    op.create_index(op.f('ix_stars_spectral_type'), 'stars', ['spectral_type'], unique=False)
    op.create_index(op.f('ix_stars_ra_dec'), 'stars', ['ra', 'dec'], unique=False)
    op.create_index(op.f('ix_stars_hip_name'), 'stars', ['hip_name'], unique=True)
    op.drop_index(op.f('ix_star_parameters_star_id'), table_name='star_parameters')
    op.create_index(op.f('ix_star_params_star_id'), 'star_parameters', ['star_id'], unique=False)
    op.drop_constraint(None, 'planets', type_='unique')
    op.create_index(op.f('ix_planets_planet_name'), 'planets', ['planet_name'], unique=True)
    op.drop_index(op.f('ix_planet_parameters_planet_id'), table_name='planet_parameters')
    op.create_index(op.f('ix_planet_params_planet_id'), 'planet_parameters', ['planet_id'], unique=False)
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=False)
    op.create_unique_constraint(op.f('papers_doi_key'), 'papers', ['doi'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('papers_arxiv_id_key'), 'papers', ['arxiv_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_orbital_predictions_unconfirmed'), 'orbital_predictions', ['predicted_at'], unique=False, postgresql_where='(confirmed_by_planet_id IS NULL)')
    op.drop_index(op.f('ix_molecule_detections_reviewed'), table_name='molecule_detections')
    op.drop_index(op.f('ix_molecule_detections_planet_id'), table_name='molecule_detections')
    op.drop_index(op.f('ix_molecule_detections_molecule'), table_name='molecule_detections')
    op.drop_index(op.f('ix_molecule_detections_detection_sigma'), table_name='molecule_detections')
    op.create_index(op.f('ix_mol_det_sigma'), 'molecule_detections', ['detection_sigma'], unique=False)
    op.create_index(op.f('ix_mol_det_reviewed'), 'molecule_detections', ['reviewed'], unique=False)
    op.create_index(op.f('ix_mol_det_planet_id'), 'molecule_detections', ['planet_id'], unique=False)
    op.create_index(op.f('ix_mol_det_molecule'), 'molecule_detections', ['molecule'], unique=False)
    op.drop_index(op.f('ix_hitran_lines_wavelength_um'), table_name='hitran_lines')
    op.drop_index(op.f('ix_hitran_lines_molecule'), table_name='hitran_lines')
    op.create_index(op.f('ix_hitran_wavelength'), 'hitran_lines', ['wavelength_um'], unique=False)
    op.create_index(op.f('ix_hitran_molecule'), 'hitran_lines', ['molecule'], unique=False)
    op.drop_index(op.f('ix_habitability_scores_planet_id'), table_name='habitability_scores')
    op.create_index(op.f('ix_habitability_planet_id'), 'habitability_scores', ['planet_id'], unique=False)
    op.create_index(op.f('ix_habitability_composite'), 'habitability_scores', ['composite_score'], unique=False, postgresql_where='(composite_score IS NOT NULL)')
    op.drop_index(op.f('ix_biosignature_detections_planet_id'), table_name='biosignature_detections')
    op.drop_index(op.f('ix_biosignature_detections_molecule'), table_name='biosignature_detections')
    op.drop_index(op.f('ix_biosignature_detections_detection_confidence'), table_name='biosignature_detections')
    op.create_index(op.f('ix_biosig_planet_id'), 'biosignature_detections', ['planet_id'], unique=False)
    op.create_index(op.f('ix_biosig_molecule'), 'biosignature_detections', ['molecule'], unique=False)
    op.create_index(op.f('ix_biosig_confidence'), 'biosignature_detections', ['detection_confidence'], unique=False)
    op.drop_index(op.f('ix_atmospheric_spectra_wavelength_um'), table_name='atmospheric_spectra')
    op.drop_index(op.f('ix_atmospheric_spectra_spec_id'), table_name='atmospheric_spectra')
    op.drop_index(op.f('ix_atmospheric_spectra_planet_name'), table_name='atmospheric_spectra')
    op.drop_index(op.f('ix_atmospheric_spectra_planet_id'), table_name='atmospheric_spectra')
    op.drop_index(op.f('ix_atmospheric_spectra_facility'), table_name='atmospheric_spectra')
    op.create_index(op.f('ix_atm_spectra_wavelength'), 'atmospheric_spectra', ['wavelength_um'], unique=False)
    op.create_index(op.f('ix_atm_spectra_spec_id'), 'atmospheric_spectra', ['spec_id'], unique=False)
    op.create_index(op.f('ix_atm_spectra_planet_name'), 'atmospheric_spectra', ['planet_name'], unique=False)
    op.create_index(op.f('ix_atm_spectra_planet_id'), 'atmospheric_spectra', ['planet_id'], unique=False)
    op.create_index(op.f('ix_atm_spectra_facility'), 'atmospheric_spectra', ['facility'], unique=False)
    op.drop_index(op.f('ix_anomaly_flags_reviewed'), table_name='anomaly_flags')
    op.drop_index(op.f('ix_anomaly_flags_planet_id'), table_name='anomaly_flags')
    op.drop_index(op.f('ix_anomaly_flags_deviation_sigma'), table_name='anomaly_flags')
    op.create_index(op.f('ix_anomaly_sigma'), 'anomaly_flags', ['deviation_sigma'], unique=False)
    op.create_index(op.f('ix_anomaly_reviewed'), 'anomaly_flags', ['reviewed'], unique=False)
    op.create_index(op.f('ix_anomaly_planet_id'), 'anomaly_flags', ['planet_id'], unique=False)
    op.create_table('paper_planet_mentions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('paper_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('star_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name_found', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.paper_id'], name=op.f('paper_planet_mentions_paper_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.planet_id'], name=op.f('paper_planet_mentions_planet_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['star_id'], ['stars.star_id'], name=op.f('paper_planet_mentions_star_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('paper_planet_mentions_pkey'))
    )
    op.create_index(op.f('ix_ppm_star_id'), 'paper_planet_mentions', ['star_id'], unique=False)
    op.create_index(op.f('ix_ppm_planet_id'), 'paper_planet_mentions', ['planet_id'], unique=False)
    op.create_index(op.f('ix_ppm_paper_id'), 'paper_planet_mentions', ['paper_id'], unique=False)
    op.create_table('exomol_lines_curated',
    sa.Column('exomol_line_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('molecule', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('wavelength_um', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('intensity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('temp_range', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('exomol_line_id', name=op.f('exomol_lines_curated_pkey'))
    )
    op.create_index(op.f('idx_exomol_mol_wl'), 'exomol_lines_curated', ['molecule', 'wavelength_um'], unique=False)
    op.drop_index(op.f('ix_spectral_templates_molecule'), table_name='spectral_templates')
    op.drop_index('ix_spectral_templates_lookup', table_name='spectral_templates')
    op.drop_table('spectral_templates')
    # ### end Alembic commands ###
