"""Add AtmosphericRetrieval table

Revision ID: 74a80e71a7a6
Revises: 2eb6e5e46115
Create Date: 2026-05-14 11:45:02.596574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74a80e71a7a6'
down_revision: Union[str, Sequence[str], None] = '2eb6e5e46115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atmospheric_retrievals',
    sa.Column('retrieval_id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('planet_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('spec_id', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('run_time_seconds', sa.Float(), nullable=True),
    sa.Column('best_fit_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence_ln_z', sa.Float(), nullable=True),
    sa.Column('posterior_file', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='running', nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.planet_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('retrieval_id')
    )
    op.create_index(op.f('ix_atmospheric_retrievals_planet_id'), 'atmospheric_retrievals', ['planet_id'], unique=False)
    op.create_index(op.f('ix_atmospheric_retrievals_spec_id'), 'atmospheric_retrievals', ['spec_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atmospheric_retrievals_spec_id'), table_name='atmospheric_retrievals')
    op.drop_index(op.f('ix_atmospheric_retrievals_planet_id'), table_name='atmospheric_retrievals')
    op.drop_table('atmospheric_retrievals')
    # ### end Alembic commands ###
